### ISSUE TITLE
Cannot resolve dependencies when trying to use latest 1.8.0

### ISSUE THREAD

**Issue by jozala-work** [michalborek/docker-microservices-gradle-plugin#8]
> Could not resolve all dependencies for configuration 'classpath'.
> Could not resolve gradle.plugin.pl.greenpath.gradle.dockermicroservices:docker-microservices-gradle-plugin:1.8.0.
>      Required by:
>          unspecified:unspecified:unspecified
>       > Could not resolve gradle.plugin.pl.greenpath.gradle.dockermicroservices:docker-microservices-gradle-plugin:1.8.0.
>          > Could not parse POM https://plugins.gradle.org/m2/gradle/plugin/pl/greenpath/gradle/dockermicroservices/docker-microservices-gradle-plugin/1.8.0/docker-microservices-gradle-plugin-1.8.0.pom
>             > Unable to resolve version for dependency 'org.codehaus.groovy:groovy-all:jar'

**Comment by michalborek** [comment]
Fixed in version 2.0.2
